Update prepsfmom.py
Hi, Mr. Esheldon, when I install ngmix in my surver I find that there is an error said that:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/home/acct-phyzj/phyzj-sirius/shenzhi/work/response/ngmix-master/ngmix/__init__.py", line 49, in <module>
    from . import ksigmamom
  File "/lustre/home/acct-phyzj/phyzj-sirius/shenzhi/work/response/ngmix-master/ngmix/ksigmamom.py", line 3, in <module>
    from ngmix.prepsfmom import KSigmaMom
  File "/lustre/home/acct-phyzj/phyzj-sirius/shenzhi/work/response/ngmix-master/ngmix/prepsfmom.py", line 4, in <module>
    import scipy.fft as fft
ModuleNotFoundError: No module named 'scipy.fft'
Then I make a change in prepsfmom.py, line 4, change 'import scipy.fft as fft' to 'from scipy import fft', then it works.
Maybe it is something wrong with scipy.
I hope this is helpful for you. Thanks!